// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8MIClQ1adkUHDx0Rq8V_bFHj_WgmBXp8',
    appId: '1:921705110989:web:f0b0293ae47d67a3f47884',
    messagingSenderId: '921705110989',
    projectId: 'medibridge-c4292',
    authDomain: 'medibridge-c4292.firebaseapp.com',
    storageBucket: 'medibridge-c4292.appspot.com',
    measurementId: 'G-RSQVFQR9DC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8MIClQ1adkUHDx0Rq8V_bFHj_WgmBXp8',
    appId: '1:921705110989:android:f0b0293ae47d67a3f47884',
    messagingSenderId: '921705110989',
    projectId: 'medibridge-c4292',
    storageBucket: 'medibridge-c4292.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8MIClQ1adkUHDx0Rq8V_bFHj_WgmBXp8',
    appId: '1:921705110989:ios:f0b0293ae47d67a3f47884',
    messagingSenderId: '921705110989',
    projectId: 'medibridge-c4292',
    storageBucket: 'medibridge-c4292.appspot.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8MIClQ1adkUHDx0Rq8V_bFHj_WgmBXp8',
    appId: '1:921705110989:ios:f0b0293ae47d67a3f47884',
    messagingSenderId: '921705110989',
    projectId: 'medibridge-c4292',
    storageBucket: 'medibridge-c4292.appspot.com',
    iosBundleId: 'com.example.myapp',
  );
}
